services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobber-auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: